### ISSUE TITLE
Error when running mvn build for 1.8 version

### ISSUE THREAD

**Issue by ajayjoe** [mkjoerg/nifi-prometheus-reporter#16]
I'm getting build failure when running mvn clean install on mac for version 1.8, hence not able to generate nar file.

This is the error I'm receiving.
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   TestPrometheusReportingTask.testOnTrigger:140 » InaccessibleObject Unable to m...
[ERROR]   TestMetricsService.testGetVirtualMachineMetrics:121 » InaccessibleObject Unabl...
[INFO] 
[ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for nifi-prometheus-bundle 1.8.0:
[INFO] 
[INFO] nifi-prometheus-bundle ............................. SUCCESS [  2.218 s]
[INFO] nifi-prometheus-reporting-task ..................... FAILURE [  3.238 s]
[INFO] nifi-prometheus-nar ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.629 s
[INFO] Finished at: 2019-01-11T14:58:42-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project nifi-prometheus-reporting-task: There are test failures.

**Comment by containerpope** [comment]
Ran fine on my machine, I created a build pipeline that pushes the nar to the release page, you can download it from there.

See: https://github.com/mkjoerg/nifi-prometheus-reporter/releases/tag/1.8.0

**Comment by ajayjoe** [comment]
Thanks for quick response.
Ajay
    On Saturday, January 12, 2019, 7:06:18 AM EST, Matthias Jörg <notifications@github.com> wrote:  
 
 
Closed #16.
