### ISSUE TITLE
Java Lang Error when enabling JVM flag

### ISSUE THREAD

**Issue by ajayjoe** [mkjoerg/nifi-prometheus-reporter#18]
Getting Java Lang reflect InaccessibleObjectException Unable to make public long. It works fine when I have the JVM flag as false

Java Version 9.0.1

Config
![image](https://user-images.githubusercontent.com/17775319/51544789-a1990600-1e2e-11e9-8deb-db08f74ed142.png)

Error

![image](https://user-images.githubusercontent.com/17775319/51544570-3e0ed880-1e2e-11e9-9a93-ccef34df642e.png)

What do I need to do?

**Comment by ajayjoe** [comment]
I was able to get it working by pointing to Java 1.8 version that I downloaded. Would be good if you can look at the changes needed for 9 or higher version of Java to take care of calls for management module.

**Comment by containerpope** [comment]
We are currently not working with Nifi anymore, but a PR would be nice, if you already updated to Java 9.
