### ISSUE TITLE
Limitation about Metrics sent to prometheus

### ISSUE THREAD

**Issue by richiesgr** [mkjoerg/nifi-prometheus-reporter#19]
Hi
As I've read this project doesn't handling custom metrics from processor.

1/ Do you mean that the only metrics that are send are only these :
process_group_amount_bytes_total 
process_group_amount_flowfiles_total
process_group_amount_items 
process_group_amount_threads_total
process_group_size_content_total Total 
push_time_seconds

2/ Is there any option to get these metrics including the processor name as tag into the metrics ?

3/ SiteToSiteMetricsReportingTask send event including processorName is it possible to combine them with your reporting task to be able to get more detailed metrics?

Thanks

**Comment by containerpope** [comment]
> 1/ Do you mean that the only metrics that are send are only these :

Yes exactly

> 2/ Is there any option to get these metrics including the processor name as tag into the metrics ?

As far as I remember these metrics can only be fetched by process group level from Nifi itself, so there shouldn't be a processor level metrics

> 3/ SiteToSiteMetricsReportingTask send event including processorName is it possible to combine them with your reporting task to be able to get more detailed metrics?

I am not sure actually, currently we aren't using Nifi anymore, we didn't dig deeper here. If you find something, a PR is always welcome :)
