### ISSUE TITLE
Process Group ID discovery

### ISSUE THREAD

**Issue by Anton-S5** [mkjoerg/nifi-prometheus-reporter#24]
Thanks for the reporting task, it's been helpful.

A question about the "Process group ID(s)" field in the task's configuration. I understand you can get metrics for a specific PG by specifying its ID, or global metrics if the field is empty. However, we've got a large number of PGs - is there a query/method for automatic discovery of PG IDs without manually specifying them?

**Comment by containerpope** [comment]
No that is not possible, you would have to do it manually.
