### ISSUE TITLE
nifi-prometheus Version NIFI compatible

### ISSUE THREAD

**Issue by maykiwo** [mkjoerg/nifi-prometheus-reporter#6]
Hello, 

I've installed and restart NIFI with this NAR.
It is correctly installed but I can see it on NIFI Cluster in section "Controller Settings" and there are nothing in the "Reporting Task" 

Is it work only for NIFI 1.6 my version is NIFI 1.2

thanks

**Comment by containerpope** [comment]
Yes the version difference should could lead to issues, because the processor is requesting stuff that is available in version 1.6 but maybe not in 1.2. 
You can try to adjust the version in the pom.xml and recompile the jar.

**Comment by maykiwo** [comment]
Thanks, it is ok
